# Generated by Django 2.0.2 on 2022-08-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='contnt',
            new_name='content',
        ),
    ]
